<?php
require_once __DIR__ . '/../app/bootstrap.php'; require_admin();
$pageTitle='Categorías';$active='categorias';$editId=(int)($_GET['edit']??0);$edit=null;
if($editId){$s=db()->prepare('SELECT * FROM categorias WHERE id=:id');$s->execute(['id'=>$editId]);$edit=$s->fetch();}
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=$_POST['action']??'save';$id=(int)($_POST['id']??0);
 if($action==='delete'){ $cnt=db()->prepare('SELECT COUNT(*) FROM productos WHERE categoria_id=:id');$cnt->execute(['id'=>$id]); if((int)$cnt->fetchColumn()>0){flash('danger','No se puede eliminar una categoría que tiene productos.');}else{db()->prepare('DELETE FROM categorias WHERE id=:id')->execute(['id'=>$id]);flash('success','Categoría eliminada.');} redirect('/categories.php'); }
 $nombre=trim((string)($_POST['nombre']??''));$descripcion=trim((string)($_POST['descripcion']??'')); if($nombre===''){flash('danger','El nombre es obligatorio.');}else{try{if($id){db()->prepare('UPDATE categorias SET nombre=:n,descripcion=:d WHERE id=:id')->execute(['n'=>$nombre,'d'=>$descripcion,'id'=>$id]);flash('success','Categoría actualizada.');}else{db()->prepare('INSERT INTO categorias(nombre,descripcion) VALUES(:n,:d)')->execute(['n'=>$nombre,'d'=>$descripcion]);flash('success','Categoría creada.');}}catch(PDOException $e){flash('danger','Ya existe una categoría con ese nombre.');}redirect('/categories.php');}
}
$cats=db()->query('SELECT c.*,COUNT(p.id) productos FROM categorias c LEFT JOIN productos p ON p.categoria_id=c.id GROUP BY c.id ORDER BY c.nombre')->fetchAll();
require __DIR__.'/../app/views/partials/header.php';
?>
<div class="page-head"><div><h1>Categorías</h1><p>Clasificación real de los productos. Solo Administrador.</p></div></div><div class="grid-2 unequal"><section class="panel"><div class="panel-head"><h2><?= $edit?'Editar categoría':'Nueva categoría' ?></h2></div><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)($edit['id']??0) ?>"><div class="field"><label>Nombre *</label><input class="form-control" name="nombre" required value="<?= e($edit['nombre']??'') ?>"></div><div class="field"><label>Descripción</label><textarea class="form-control" name="descripcion" rows="4"><?= e($edit['descripcion']??'') ?></textarea></div><button class="btn btn-primary"><?= $edit?'Guardar cambios':'Crear categoría' ?></button><?php if($edit):?><a class="btn btn-ghost" href="/categories.php">Cancelar</a><?php endif;?></form></section><section class="panel"><div class="table-wrap"><table><thead><tr><th>Categoría</th><th>Productos</th><th>Acciones</th></tr></thead><tbody><?php foreach($cats as $c):?><tr><td><strong><?= e($c['nombre']) ?></strong><small class="block"><?= e($c['descripcion']) ?></small></td><td><?= (int)$c['productos'] ?></td><td class="actions"><a class="btn-icon" href="/categories.php?edit=<?= (int)$c['id'] ?>">✏️</a><form method="post" onsubmit="return confirm('¿Eliminar categoría?')"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= (int)$c['id'] ?>"><button class="btn-icon danger">🗑️</button></form></td></tr><?php endforeach;?></tbody></table></div></section></div>
<?php require __DIR__.'/../app/views/partials/footer.php'; ?>