<?php
require_once __DIR__ . '/../app/bootstrap.php';require_login();$pageTitle='Reportes';$active='reportes';
$stats=db()->query("SELECT COUNT(*) total,COALESCE(SUM(stock),0) unidades,COALESCE(SUM(precio*stock),0) valor,COUNT(*) FILTER(WHERE stock<=stock_minimo) alertas,COUNT(*) FILTER(WHERE stock=0) agotados FROM productos")->fetch();
$byCat=db()->query('SELECT c.nombre,COUNT(p.id) productos,COALESCE(SUM(p.stock),0) unidades,COALESCE(SUM(p.precio*p.stock),0) valor FROM categorias c LEFT JOIN productos p ON p.categoria_id=c.id GROUP BY c.id,c.nombre ORDER BY valor DESC')->fetchAll();
require __DIR__.'/../app/views/partials/header.php';
?>
<div class="page-head"><div><h1>Reportes</h1><p>Resumen del inventario y exportaciones.</p></div><button class="btn btn-secondary" onclick="window.print()">🖨️ Imprimir</button></div><div class="stats-grid"><div class="stat-card"><div class="stat-icon">📦</div><div><span>Productos</span><strong><?= (int)$stats['total'] ?></strong><small><?= (int)$stats['unidades'] ?> unidades</small></div></div><div class="stat-card"><div class="stat-icon warning">⚠️</div><div><span>Alertas</span><strong><?= (int)$stats['alertas'] ?></strong><small><?= (int)$stats['agotados'] ?> agotados</small></div></div><div class="stat-card"><div class="stat-icon success">💰</div><div><span>Valor total</span><strong><?= e(money($stats['valor'])) ?></strong><small>Inventario valorizado</small></div></div><div class="stat-card"><div class="stat-icon info">📄</div><div><span>Exportar</span><strong>CSV</strong><small>Compatible con Excel</small></div></div></div>
<div class="report-actions"><a class="report-card" href="/export_report.php?type=inventory"><span>📦</span><div><strong>Inventario actual</strong><small>Todos los productos y existencias</small></div><b>Descargar CSV →</b></a><a class="report-card" href="/export_report.php?type=low"><span>⚠️</span><div><strong>Productos con stock bajo</strong><small>Solo productos que requieren reposición</small></div><b>Descargar CSV →</b></a></div>
<section class="panel"><div class="panel-head"><h2>Resumen por categoría</h2></div><div class="table-wrap"><table><thead><tr><th>Categoría</th><th>Productos</th><th>Unidades</th><th>Valor</th></tr></thead><tbody><?php foreach($byCat as $r):?><tr><td><strong><?= e($r['nombre']) ?></strong></td><td><?= (int)$r['productos'] ?></td><td><?= (int)$r['unidades'] ?></td><td><?= e(money($r['valor'])) ?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php require __DIR__.'/../app/views/partials/footer.php'; ?>