<?php
require_once __DIR__ . '/../app/bootstrap.php'; require_admin();
$pageTitle='Usuarios';$active='usuarios';$editId=(int)($_GET['edit']??0);$edit=null;if($editId){$s=db()->prepare('SELECT id,nombre,usuario,rol,activo FROM usuarios WHERE id=:id');$s->execute(['id'=>$editId]);$edit=$s->fetch();}
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=$_POST['action']??'save';$id=(int)($_POST['id']??0);
 if($action==='toggle'){if($id===(int)current_user()['id']){flash('danger','No puedes desactivar tu propia cuenta.');}else{db()->prepare('UPDATE usuarios SET activo=NOT activo WHERE id=:id')->execute(['id'=>$id]);flash('success','Estado del usuario actualizado.');}redirect('/users.php');}
 $nombre=trim((string)($_POST['nombre']??''));$usuario=trim((string)($_POST['usuario']??''));$rol=(string)($_POST['rol']??'ENCARGADO');$password=(string)($_POST['password']??''); if($nombre===''||$usuario===''||!in_array($rol,['ADMIN','ENCARGADO'],true)){flash('danger','Completa correctamente los datos.');redirect('/users.php'.($id?'?edit='.$id:''));}
 try{if($id){if($password!==''){$sql='UPDATE usuarios SET nombre=:n,usuario=:u,rol=:r,password_hash=:p WHERE id=:id';$params=['n'=>$nombre,'u'=>$usuario,'r'=>$rol,'p'=>password_hash($password,PASSWORD_DEFAULT),'id'=>$id];}else{$sql='UPDATE usuarios SET nombre=:n,usuario=:u,rol=:r WHERE id=:id';$params=['n'=>$nombre,'u'=>$usuario,'r'=>$rol,'id'=>$id];}db()->prepare($sql)->execute($params);flash('success','Usuario actualizado.');}else{if($password===''){flash('danger','La contraseña es obligatoria para un usuario nuevo.');redirect('/users.php');}db()->prepare('INSERT INTO usuarios(nombre,usuario,password_hash,rol) VALUES(:n,:u,:p,:r)')->execute(['n'=>$nombre,'u'=>$usuario,'p'=>password_hash($password,PASSWORD_DEFAULT),'r'=>$rol]);flash('success','Usuario creado.');}}catch(PDOException $e){flash('danger','El nombre de usuario ya está en uso.');}redirect('/users.php');
}
$users=db()->query('SELECT id,nombre,usuario,rol,activo,fecha_creacion,ultimo_acceso FROM usuarios ORDER BY id')->fetchAll();require __DIR__.'/../app/views/partials/header.php';
?>
<div class="page-head"><div><h1>Usuarios del sistema</h1><p>Cuentas privadas creadas por el Administrador.</p></div></div><div class="grid-2 unequal"><section class="panel"><div class="panel-head"><h2><?= $edit?'Editar usuario':'Nuevo usuario' ?></h2></div><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)($edit['id']??0) ?>"><div class="field"><label>Nombre *</label><input class="form-control" name="nombre" required value="<?= e($edit['nombre']??'') ?>"></div><div class="field"><label>Usuario *</label><input class="form-control" name="usuario" required value="<?= e($edit['usuario']??'') ?>"></div><div class="field"><label>Rol *</label><select class="form-control" name="rol"><option value="ENCARGADO" <?= ($edit['rol']??'')==='ENCARGADO'?'selected':'' ?>>Encargado</option><option value="ADMIN" <?= ($edit['rol']??'')==='ADMIN'?'selected':'' ?>>Administrador</option></select></div><div class="field"><label><?= $edit?'Nueva contraseña (opcional)':'Contraseña *' ?></label><input class="form-control" type="password" name="password" <?= $edit?'':'required' ?>></div><button class="btn btn-primary"><?= $edit?'Guardar cambios':'Crear usuario' ?></button><?php if($edit):?><a class="btn btn-ghost" href="/users.php">Cancelar</a><?php endif;?></form></section><section class="panel"><div class="table-wrap"><table><thead><tr><th>Usuario</th><th>Rol</th><th>Estado</th><th>Acciones</th></tr></thead><tbody><?php foreach($users as $u):?><tr><td><strong><?= e($u['nombre']) ?></strong><small class="block">@<?= e($u['usuario']) ?></small></td><td><span class="status info"><?= e($u['rol']) ?></span></td><td><span class="status <?= $u['activo']?'success':'danger' ?>"><?= $u['activo']?'Activo':'Inactivo' ?></span></td><td class="actions"><a class="btn-icon" href="/users.php?edit=<?= (int)$u['id'] ?>">✏️</a><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?= (int)$u['id'] ?>"><button class="btn-icon" title="Activar/Desactivar">⏻</button></form></td></tr><?php endforeach;?></tbody></table></div></section></div>
<?php require __DIR__.'/../app/views/partials/footer.php'; ?>